<a href="https://colab.research.google.com/github/sudiksa1307/AKSPI-Project/blob/main/week2_sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import sqlite3

df = pd.read_csv("https://raw.githubusercontent.com/sudiksa1307/AKSPI-Project/refs/heads/main/heart_disease.csv")
df = df.drop_duplicates().dropna()
df.columns = (
    df.columns.str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [7]:
conn = sqlite3.connect(":memory:")
df.to_sql("data", conn, index=False)

def q(sql):
    return pd.read_sql(sql, conn)

In [8]:
q("SELECT * FROM data LIMIT 5")

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,32,1,2,107,196.0,1.0,0.0,159.0,0.0,1.8,2.0,0.0,?,0
1,66,1,2,112,240.0,?,0.0,148.0,0.0,0.7,2.0,0.0,?,0
2,60,0,2,123,209.0,0.0,0.0,114.0,0.0,1.1,2.0,1.0,3.0,1
3,49,0,3,105,167.0,0.0,0.0,142.0,0.0,0.1,1.0,1.0,3.0,0
4,49,1,2,114,261.0,0.0,0.0,188.0,1.0,0.1,3.0,0.0,7.0,1

In [9]:
q("SELECT COUNT(*) AS total_rows FROM data")

   total_rows
0        5000

In [10]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol         object
fbs          object
restecg      object
thalach      object
exang        object
oldpeak     float64
slope        object
ca           object
thal         object
num           int64
dtype: object

My table has 5,000 rows.
One row represents one patient record.
Number to measure: percentage of patients with heart disease, using the num column.
Groups to compare: sex.

In [12]:
q("""
SELECT COUNT(*) AS patient_count
FROM data
WHERE sex = 0
""")

   patient_count
0           1329

In [11]:
q("""
SELECT COUNT(*) AS patient_count
FROM data
WHERE sex = 1
""")

   patient_count
0           3671

In [13]:
q("""
SELECT sex,
       COUNT(*) AS patient_count
FROM data
GROUP BY sex
""")

   sex  patient_count
0    0           1329
1    1           3671

In [14]:
q("""
SELECT sex,
       COUNT(*) AS patient_count
FROM data
GROUP BY sex
ORDER BY patient_count DESC
LIMIT 5
""")

   sex  patient_count
0    1           3671
1    0           1329

Q1: How many patient records show heart disease?
Columns needed: num
Q2: Which sex group has the highest percentage of patients with heart disease?
Columns needed: sex, num
Q3: What are the top five ages by number of heart disease cases among patients with sex = 1?
Columns needed: age, sex, num

In [15]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num'],
      dtype='object')